const clinics = [
  {
    name: "Clinica Sala Palatului",
    type: "Medical Clinic",
    distanceToCenter: "0.2 km to City center",
    rating: 4.9,
    reviews: 68,
    address: "Str. Ion Campineanu nr. 23, Sector 1, BUCURESTI",
    size: 120,
    doctorsCount: 10,
    image: "https://via.placeholder.com/300",
    mapLink: "https://maps.google.com/?q=Clinica+Sala+Palatului",
    description:
      "Set in a central area of Bucharest, 400 meters from the Black Tower and 300 meters from Council Square, Clinica Sala Palatului offers air-conditioned accommodation with a balcony and free WiFi.",
    amenities: ["Free WiFi", "Parking", "AC", "Balcony/Patio"],
  },
  {
    name: "Clinica Victoria",
    type: "Dental Clinic",
    distanceToCenter: "0.5 km to City center",
    rating: 4.8,
    reviews: 54,
    address: "Bd. Victoria nr. 45, Sector 1, BUCURESTI",
    size: 90,
    doctorsCount: 8,
    image: "https://via.placeholder.com/300",
    mapLink: "https://maps.google.com/?q=Clinica+Victoria",
    description:
      "Located in the heart of Bucharest, Clinica Victoria offers state-of-the-art dental services with a focus on patient comfort and care.",
    amenities: ["Free WiFi", "TV/Entertainment", "AC", "Parking"],
  },
  {
    name: "Clinica Sanitas",
    type: "General Clinic",
    distanceToCenter: "1.0 km to City center",
    rating: 4.7,
    reviews: 40,
    address: "Str. Sanitas nr. 12, Sector 2, BUCURESTI",
    size: 150,
    doctorsCount: 15,
    image: "https://via.placeholder.com/300",
    mapLink: "https://maps.google.com/?q=Clinica+Sanitas",
    description:
      "Clinica Sanitas provides comprehensive medical services with a team of experienced doctors and modern facilities.",
    amenities: ["Free WiFi", "Parking", "AC", "Kitchen/Kitchenette"],
  },
  {
    name: "Clinica MedLife",
    type: "Pediatric Clinic",
    distanceToCenter: "1.5 km to City center",
    rating: 4.6,
    reviews: 75,
    address: "Str. MedLife nr. 30, Sector 3, BUCURESTI",
    size: 200,
    doctorsCount: 20,
    image: "https://via.placeholder.com/300",
    mapLink: "https://maps.google.com/?q=Clinica+MedLife",
    description:
      "Specializing in pediatric care, Clinica MedLife offers a wide range of services for children with a focus on friendly and comfortable treatments.",
    amenities: ["Free WiFi", "Play Area", "AC", "Parking"],
  },
  {
    name: "Clinica Nova",
    type: "Orthopedic Clinic",
    distanceToCenter: "2.0 km to City center",
    rating: 4.5,
    reviews: 32,
    address: "Str. Nova nr. 21, Sector 4, BUCURESTI",
    size: 110,
    doctorsCount: 12,
    image: "https://via.placeholder.com/300",
    mapLink: "https://maps.google.com/?q=Clinica+Nova",
    description:
      "Clinica Nova is renowned for its orthopedic services, offering advanced treatments and personalized care plans for patients.",
    amenities: ["Free WiFi", "Gym", "AC", "Parking"],
  },
];

export default clinics;
