const cities = [
  { id: 1, countyId: 1, label: "Bucharest" },
  { id: 2, countyId: 2, label: "Cluj-Napoca" },
  { id: 3, countyId: 3, label: "Timișoara" },
  { id: 4, countyId: 4, label: "Iași" },
  { id: 5, countyId: 5, label: "Constanța" },
  { id: 6, countyId: 6, label: "Craiova" },
  { id: 7, countyId: 7, label: "Brașov" },
  { id: 8, countyId: 8, label: "Galați" },
  { id: 9, countyId: 9, label: "Ploiești" },
  { id: 10, countyId: 10, label: "Oradea" },
  { id: 11, countyId: 11, label: "Brăila" },
  { id: 12, countyId: 12, label: "Arad" },
  { id: 13, countyId: 13, label: "Pitești" },
  { id: 14, countyId: 14, label: "Sibiu" },
  { id: 15, countyId: 15, label: "Bacău" },
  { id: 16, countyId: 16, label: "Târgu Mureș" },
  { id: 17, countyId: 17, label: "Baia Mare" },
  { id: 18, countyId: 18, label: "Buzău" },
  { id: 19, countyId: 19, label: "Botoșani" },
  { id: 20, countyId: 20, label: "Satu Mare" },
  { id: 21, countyId: 21, label: "Râmnicu Vâlcea" },
  { id: 22, countyId: 22, label: "Drobeta-Turnu Severin" },
  { id: 23, countyId: 23, label: "Suceava" },
  { id: 24, countyId: 24, label: "Piatra Neamț" },
  { id: 25, countyId: 25, label: "Târgu Jiu" },
  { id: 26, countyId: 26, label: "Focșani" },
  { id: 27, countyId: 27, label: "Bistrița" },
  { id: 28, countyId: 28, label: "Tulcea" },
  { id: 29, countyId: 29, label: "Reșița" },
  { id: 30, countyId: 30, label: "Slatina" },
  { id: 31, countyId: 31, label: "Vaslui" },
  { id: 32, countyId: 32, label: "Alba Iulia" },
  { id: 33, countyId: 33, label: "Giurgiu" },
  { id: 34, countyId: 34, label: "Deva" },
  { id: 35, countyId: 35, label: "Hunedoara" },
  { id: 36, countyId: 36, label: "Zalău" },
  { id: 37, countyId: 37, label: "Sfântu Gheorghe" },
  { id: 38, countyId: 38, label: "Roman" },
  { id: 39, countyId: 39, label: "Odorheiu Secuiesc" },
  { id: 40, countyId: 40, label: "Miercurea Ciuc" },
  { id: 41, countyId: 41, label: "Turda" },
  { id: 42, countyId: 42, label: "Mediaș" },
  { id: 43, countyId: 43, label: "Slobozia" },
  { id: 44, countyId: 44, label: "Alexandria" },
  { id: 45, countyId: 45, label: "Voluntari" },
  { id: 46, countyId: 46, label: "Lugoj" },
  { id: 47, countyId: 47, label: "Medgidia" },
  { id: 48, countyId: 48, label: "Onești" },
  { id: 49, countyId: 49, label: "Mangalia" },
  { id: 50, countyId: 50, label: "Tecuci" },
  { id: 51, countyId: 51, label: "Petroșani" },
  { id: 52, countyId: 52, label: "Odorheiu Secuiesc" },
  { id: 53, countyId: 53, label: "Mangalia" },
  { id: 54, countyId: 54, label: "Roman" },
  { id: 55, countyId: 55, label: "Făgăraș" },
  { id: 56, countyId: 56, label: "Bârlad" },
  { id: 57, countyId: 57, label: "Câmpina" },
  { id: 58, countyId: 58, label: "Călărași" },
  { id: 59, countyId: 59, label: "Pașcani" },
  { id: 60, countyId: 60, label: "Sighișoara" },
  { id: 61, countyId: 61, label: "Curtea de Argeș" },
  { id: 62, countyId: 62, label: "Câmpulung" },
  { id: 63, countyId: 63, label: "Târgu Neamț" },
  { id: 64, countyId: 64, label: "Sighetu Marmației" },
  { id: 65, countyId: 65, label: "Caracal" },
  { id: 66, countyId: 66, label: "Gheorgheni" },
  { id: 67, countyId: 67, label: "Fălticeni" },
  { id: 68, countyId: 68, label: "Hârlău" },
  { id: 69, countyId: 69, label: "Bocșa" },
  { id: 70, countyId: 70, label: "Dărmănești" },
  { id: 71, countyId: 71, label: "Dorohoi" },
  { id: 72, countyId: 72, label: "Bicaz" },
  { id: 73, countyId: 73, label: "Negrești-Oaș" },
  { id: 74, countyId: 74, label: "Sebiş" },
  { id: 75, countyId: 75, label: "Cisnădie" },
  { id: 76, countyId: 76, label: "Borșa" },
  { id: 77, countyId: 77, label: "Vlăhița" },
  { id: 78, countyId: 78, label: "Costești" },
  { id: 79, countyId: 79, label: "Oravița" },
  { id: 80, countyId: 80, label: "Târgu Lăpuș" },
  { id: 81, countyId: 81, label: "Năsăud" },
  { id: 82, countyId: 82, label: "Blaj" },
  { id: 83, countyId: 83, label: "Brad" },
  { id: 84, countyId: 84, label: "Sânnicolau Mare" },
  { id: 85, countyId: 85, label: "Vișeu de Sus" },
  { id: 86, countyId: 86, label: "Cugir" },
  { id: 87, countyId: 87, label: "Găești" },
  { id: 88, countyId: 88, label: "Balș" },
  { id: 89, countyId: 89, label: "Comănești" },
  { id: 90, countyId: 90, label: "Buftea" },
  { id: 91, countyId: 91, label: "Ștei" },
  { id: 92, countyId: 92, label: "Buhuși" },
  { id: 93, countyId: 93, label: "Cehu Silvaniei" },
  { id: 94, countyId: 94, label: "Simeria" },
  { id: 95, countyId: 95, label: "Băicoi" },
  { id: 96, countyId: 96, label: "Tășnad" },
  { id: 97, countyId: 97, label: "Mizil" },
  { id: 98, countyId: 98, label: "Toplița" },
  { id: 99, countyId: 99, label: "Geoagiu" },
  { id: 100, countyId: 100, label: "Sângeorz-Băi" },
  { id: 101, countyId: 101, label: "Chitila" },
  { id: 102, countyId: 102, label: "Târgu Frumos" },
  { id: 103, countyId: 103, label: "Fierbinți-Târg" },
  { id: 104, countyId: 104, label: "Târgu Ocna" },
  { id: 105, countyId: 105, label: "Călan" },
  { id: 106, countyId: 106, label: "Victoria" },
  { id: 107, countyId: 107, label: "Cajvana" },
  { id: 108, countyId: 108, label: "Darabani" },
  { id: 109, countyId: 109, label: "Oțelu Roșu" },
  { id: 110, countyId: 110, label: "Panciu" },
  { id: 111, countyId: 111, label: "Beiuș" },
  { id: 112, countyId: 112, label: "Babadag" },
  { id: 113, countyId: 113, label: "Rădăuți" },
  { id: 114, countyId: 114, label: "Gherla" },
  { id: 115, countyId: 115, label: "Baia Sprie" },
  { id: 116, countyId: 116, label: "Valea lui Mihai" },
  { id: 117, countyId: 117, label: "Ocna Mureș" },
  { id: 118, countyId: 118, label: "Vulcan" },
  { id: 119, countyId: 119, label: "Zimnicea" },
  { id: 120, countyId: 120, label: "Uricani" },
  { id: 121, countyId: 121, label: "Bușteni" },
  { id: 122, countyId: 122, label: "Aleșd" },
  { id: 123, countyId: 123, label: "Bolintin-Vale" },
  { id: 124, countyId: 124, label: "Năvodari" },
  { id: 125, countyId: 125, label: "Otopeni" },
  { id: 126, countyId: 126, label: "Făurei" },
  { id: 127, countyId: 127, label: "Motru" },
  { id: 128, countyId: 128, label: "Băile Tușnad" },
  { id: 129, countyId: 129, label: "Săcele" },
  { id: 130, countyId: 130, label: "Cernavodă" },
  { id: 131, countyId: 131, label: "Sovata" },
  { id: 132, countyId: 132, label: "Ineu" },
  { id: 133, countyId: 133, label: "Târgu Secuiesc" },
  { id: 134, countyId: 134, label: "Măgurele" },
  { id: 135, countyId: 135, label: "Borșa" },
  { id: 136, countyId: 136, label: "Drăgășani" },
  { id: 137, countyId: 137, label: "Miercurea Sibiului" },
  { id: 138, countyId: 138, label: "Negrești" },
  { id: 139, countyId: 139, label: "Turnu Măgurele" },
  { id: 140, countyId: 140, label: "Mărășești" },
  { id: 141, countyId: 141, label: "Târgu Cărbunești" },
  { id: 142, countyId: 142, label: "Huedin" },
  { id: 143, countyId: 143, label: "Bocșa" },
  { id: 144, countyId: 144, label: "Potcoava" },
  { id: 145, countyId: 145, label: "Flămânzi" },
  { id: 146, countyId: 146, label: "Tășnad" },
  { id: 147, countyId: 147, label: "Hârlău" },
  { id: 148, countyId: 148, label: "Sântana" },
  { id: 149, countyId: 149, label: "Câmpulung Moldovenesc" },
  { id: 150, countyId: 150, label: "Codlea" },
  { id: 151, countyId: 151, label: "Rovinari" },
  { id: 152, countyId: 152, label: "Petrila" },
  { id: 153, countyId: 153, label: "Moldova Nouă" },
  { id: 154, countyId: 154, label: "Țăndărei" },
  { id: 155, countyId: 155, label: "Popești-Leordeni" },
  { id: 156, countyId: 156, label: "Buhuși" },
  { id: 157, countyId: 157, label: "Baia de Arieș" },
  { id: 158, countyId: 158, label: "Murgeni" },
  { id: 159, countyId: 159, label: "Siret" },
  { id: 160, countyId: 160, label: "Băile Govora" },
  { id: 161, countyId: 161, label: "Arad" },
  { id: 162, countyId: 162, label: "Curtici" },
  { id: 163, countyId: 163, label: "Buziaș" },
  { id: 164, countyId: 164, label: "Lipova" },
  { id: 165, countyId: 165, label: "Aiud" },
  { id: 166, countyId: 166, label: "Târgu Neamț" },
  { id: 167, countyId: 167, label: "Cugir" },
  { id: 168, countyId: 168, label: "Zalău" },
  { id: 169, countyId: 169, label: "Sânnicolau Mare" },
  { id: 170, countyId: 170, label: "Făget" },
  { id: 171, countyId: 171, label: "Ineu" },
  { id: 172, countyId: 172, label: "Gura Humorului" },
  { id: 173, countyId: 173, label: "Pașcani" },
  { id: 174, countyId: 174, label: "Năvodari" },
  { id: 175, countyId: 175, label: "Buftea" },
  { id: 176, countyId: 176, label: "Târgu Secuiesc" },
  { id: 177, countyId: 177, label: "Caransebeș" },
  { id: 178, countyId: 178, label: "Câmpulung Moldovenesc" },
  { id: 179, countyId: 179, label: "Hârșova" },
  { id: 180, countyId: 180, label: "Mangalia" },
  { id: 181, countyId: 181, label: "Turnu Măgurele" },
  { id: 182, countyId: 182, label: "Panciu" },
  { id: 183, countyId: 183, label: "Brăila" },
  { id: 184, countyId: 184, label: "Urziceni" },
  { id: 185, countyId: 185, label: "Băicoi" },
];
export default cities;
