const romanianCounties = [
  { id: "AB", label: "Alba" },
  { id: "AR", label: "Arad" },
  { id: "AG", label: "Argeș" },
  { id: "BC", label: "Bacău" },
  { id: "BH", label: "Bihor" },
  { id: "BN", label: "Bistrița-Năsăud" },
  { id: "BR", label: "Brăila" },
  { id: "BT", label: "Botoșani" },
  { id: "BV", label: "Brașov" },
  { id: "BZ", label: "Buzău" },
  { id: "CS", label: "Caraș-Severin" },
  { id: "CL", label: "Călărași" },
  { id: "CJ", label: "Cluj" },
  { id: "CT", label: "Constanța" },
  { id: "CV", label: "Covasna" },
  { id: "DB", label: "Dâmbovița" },
  { id: "DJ", label: "Dolj" },
  { id: "GL", label: "Galați" },
  { id: "GR", label: "Giurgiu" },
  { id: "GJ", label: "Gorj" },
  { id: "HR", label: "Harghita" },
  { id: "HD", label: "Hunedoara" },
  { id: "IL", label: "Ialomița" },
  { id: "IS", label: "Iași" },
  { id: "IF", label: "Ilfov" },
  { id: "MM", label: "Maramureș" },
  { id: "MH", label: "Mehedinți" },
  { id: "MS", label: "Mureș" },
  { id: "NT", label: "Neamț" },
  { id: "OT", label: "Olt" },
  { id: "PH", label: "Prahova" },
  { id: "SM", label: "Satu Mare" },
  { id: "SJ", label: "Sălaj" },
  { id: "SB", label: "Sibiu" },
  { id: "SV", label: "Suceava" },
  { id: "TR", label: "Teleorman" },
  { id: "TM", label: "Timiș" },
  { id: "TL", label: "Tulcea" },
  { id: "VS", label: "Vaslui" },
  { id: "VL", label: "Vâlcea" },
  { id: "VN", label: "Vrancea" },
  { id: "B", label: "București" },
];
export default romanianCounties;
