// mockData.js
const generateMockPatients = (num) => {
  const patients = [];
  for (let i = 1; i <= num; i++) {
    patients.push({
      id: i,
      photo: `https://randomuser.me/api/portraits/men/${i % 100}.jpg`,
      name: `John Doe ${i}`,
      age: 20 + (i % 50),
      gender: i % 2 === 0 ? "Male" : "Female",
      height: 160 + (i % 40),
      weight: 60 + (i % 50),
      bloodType: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"][i % 8],
      address: `City ${i}, Country`,
      phone: `+407${Math.floor(10000000 + Math.random() * 90000000)}`,
      email: `john.doe${i}@example.com`,
      sportFrequency: `${i % 7} times per week`,
      familyStatus: i % 2 === 0 ? "Single" : "Married",
      profession: "Software Developer",
      appointments: [
        {
          id: i,
          date: `2023-06-${(i % 30) + 1}`,
          medic: `Dr. Smith ${i}`,
          reason: "Routine check-up",
          department: "General Medicine",
          medicalService: "Consultation",
          diagnostic: "Healthy",
        },
      ],
    });
  }
  return patients;
};
export const patients = [
  {
    id: 1,
    photo: `https://randomuser.me/api/portraits/men/1.jpg`,
    name: "Andrei Popescu",
    age: 30,
    gender: "Male",
    height: 180,
    weight: 75,
    bloodType: "A+",
    address: "Strada Cuza Voda, Iasi, Romania",
    phone: "+40724123456",
    email: "andrei.popescu@example.com",
    sportFrequency: "3 times per week",
    familyStatus: "Single",
    profession: "Software Developer",
    appointments: [
      {
        id: 1,
        date: "2023-06-15",
        medic: "Dr. Smith 1",
        reason: "Routine check-up",
        department: "General Medicine",
        medicalService: "Consultation",
        diagnostic: "Healthy",
      },
    ],
  },
  {
    id: 2,
    photo: `https://randomuser.me/api/portraits/women/2.jpg`,
    name: "Maria Ionescu",
    age: 25,
    gender: "Female",
    height: 165,
    weight: 60,
    bloodType: "B+",
    address: "Bulevardul Stefan cel Mare, Iasi, Romania",
    phone: "+40725123456",
    email: "maria.ionescu@example.com",
    sportFrequency: "2 times per week",
    familyStatus: "Married",
    profession: "Teacher",
    appointments: [
      {
        id: 2,
        date: "2023-06-20",
        medic: "Dr. Smith 2",
        reason: "Headache",
        department: "Neurology",
        medicalService: "Consultation",
        diagnostic: "Migraine",
      },
    ],
  },
  {
    id: 3,
    photo: `https://randomuser.me/api/portraits/men/3.jpg`,
    name: "Bogdan Mihai",
    age: 40,
    gender: "Male",
    height: 175,
    weight: 80,
    bloodType: "O-",
    address: "Strada Mihai Eminescu, Iasi, Romania",
    phone: "+40726123456",
    email: "bogdan.mihai@example.com",
    sportFrequency: "5 times per week",
    familyStatus: "Single",
    profession: "Lawyer",
    appointments: [
      {
        id: 3,
        date: "2023-06-25",
        medic: "Dr. Smith 3",
        reason: "Chest pain",
        department: "Cardiology",
        medicalService: "EKG",
        diagnostic: "Healthy",
      },
    ],
  },
  {
    id: 4,
    photo: `https://randomuser.me/api/portraits/women/4.jpg`,
    name: "Elena Georgescu",
    age: 35,
    gender: "Female",
    height: 170,
    weight: 65,
    bloodType: "AB+",
    address: "Strada Alexandru cel Bun, Iasi, Romania",
    phone: "+40727123456",
    email: "elena.georgescu@example.com",
    sportFrequency: "4 times per week",
    familyStatus: "Married",
    profession: "Accountant",
    appointments: [
      {
        id: 4,
        date: "2023-06-10",
        medic: "Dr. Smith 4",
        reason: "Back pain",
        department: "Orthopedics",
        medicalService: "Consultation",
        diagnostic: "Muscle strain",
      },
    ],
  },
  {
    id: 5,
    photo: `https://randomuser.me/api/portraits/men/5.jpg`,
    name: "George Vasilescu",
    age: 50,
    gender: "Male",
    height: 185,
    weight: 90,
    bloodType: "B-",
    address: "Strada Vasile Alecsandri, Iasi, Romania",
    phone: "+40728123456",
    email: "george.vasilescu@example.com",
    sportFrequency: "1 time per week",
    familyStatus: "Married",
    profession: "Engineer",
    appointments: [
      {
        id: 5,
        date: "2023-06-05",
        medic: "Dr. Smith 5",
        reason: "Knee pain",
        department: "Orthopedics",
        medicalService: "MRI",
        diagnostic: "Arthritis",
      },
    ],
  },
  {
    id: 6,
    photo: `https://randomuser.me/api/portraits/women/6.jpg`,
    name: "Ioana Preda",
    age: 28,
    gender: "Female",
    height: 168,
    weight: 58,
    bloodType: "O+",
    address: "Strada Independentei, Iasi, Romania",
    phone: "+40729123456",
    email: "ioana.preda@example.com",
    sportFrequency: "5 times per week",
    familyStatus: "Single",
    profession: "Nurse",
    appointments: [
      {
        id: 6,
        date: "2023-06-18",
        medic: "Dr. Smith 6",
        reason: "Stomach pain",
        department: "Gastroenterology",
        medicalService: "Endoscopy",
        diagnostic: "Gastritis",
      },
    ],
  },
  {
    id: 7,
    photo: `https://randomuser.me/api/portraits/men/7.jpg`,
    name: "Radu Balan",
    age: 45,
    gender: "Male",
    height: 178,
    weight: 85,
    bloodType: "A-",
    address: "Strada Sf. Lazăr, Iasi, Romania",
    phone: "+40730123456",
    email: "radu.balan@example.com",
    sportFrequency: "2 times per week",
    familyStatus: "Married",
    profession: "Architect",
    appointments: [
      {
        id: 7,
        date: "2023-06-22",
        medic: "Dr. Smith 7",
        reason: "Skin rash",
        department: "Dermatology",
        medicalService: "Consultation",
        diagnostic: "Allergic reaction",
      },
    ],
  },
  {
    id: 8,
    photo: `https://randomuser.me/api/portraits/women/8.jpg`,
    name: "Ana Dumitrescu",
    age: 32,
    gender: "Female",
    height: 162,
    weight: 55,
    bloodType: "AB-",
    address: "Strada Pacurari, Iasi, Romania",
    phone: "+40731123456",
    email: "ana.dumitrescu@example.com",
    sportFrequency: "4 times per week",
    familyStatus: "Single",
    profession: "Pharmacist",
    appointments: [
      {
        id: 8,
        date: "2023-06-12",
        medic: "Dr. Smith 8",
        reason: "Eye pain",
        department: "Ophthalmology",
        medicalService: "Consultation",
        diagnostic: "Conjunctivitis",
      },
    ],
  },
  {
    id: 9,
    photo: `https://randomuser.me/api/portraits/men/9.jpg`,
    name: "Mihai Radulescu",
    age: 38,
    gender: "Male",
    height: 182,
    weight: 82,
    bloodType: "B+",
    address: "Strada Nicolina, Iasi, Romania",
    phone: "+40732123456",
    email: "mihai.radulescu@example.com",
    sportFrequency: "3 times per week",
    familyStatus: "Married",
    profession: "Chef",
    appointments: [
      {
        id: 9,
        date: "2023-06-08",
        medic: "Dr. Smith 9",
        reason: "Toothache",
        department: "Dentistry",
        medicalService: "Consultation",
        diagnostic: "Cavity",
      },
    ],
  },
  {
    id: 10,
    photo: `https://randomuser.me/api/portraits/women/10.jpg`,
    name: "Gabriela Enescu",
    age: 29,
    gender: "Female",
    height: 167,
    weight: 60,
    bloodType: "A+",
    address: "Strada Tatarasi, Iasi, Romania",
    phone: "+40733123456",
    email: "gabriela.enescu@example.com",
    sportFrequency: "5 times per week",
    familyStatus: "Single",
    profession: "Journalist",
    appointments: [
      {
        id: 10,
        date: "2023-06-30",
        medic: "Dr. Smith 10",
        reason: "Fatigue",
        department: "General Medicine",
        medicalService: "Consultation",
        diagnostic: "Anemia",
      },
    ],
  },
];

// export const patients = generateMockPatients(100);
export const appointments = patients.flatMap((patient) => patient.appointments);
export const getAppointmentsByPatientId = (id) =>
  patients.filter((patient) => patient.id === id)[0].appointments;
